FROM node:18

WORKDIR /usr/src/app

COPY src/package*.json ./

# Install dependencies with verbose output for debugging
RUN npm install --verbose

# COPY . .
COPY src/ .

EXPOSE 3000

# CMD ["npm", "start"]
# CMD ["node", "server.js"]
CMD ["node", "src/server.js"]